export const SITE_CONFIG = {
  id: 'research',
  name: 'DreamIT Research',
  nameKo: '인적자원관리(HRM)',
  description: '채용, 교육, 성과관리, 보상, 노사관계, 조직문화 등 HRM의 모든 것을 체계적으로 학습하는 플랫폼',
  url: 'https://research.dreamitbiz.com',
  base: '/',
  author: 'DreamIT Biz',
  email: 'aebon@dreamitbiz.com',
  github: 'https://github.com/aebonlee/Research',
  dbPrefix: 'research_',
};

export const LEARNING_PATHS = [
  {
    id: 'hrm-intro',
    icon: 'fa-users-gear',
    nameKo: '인적자원관리 개론',
    nameEn: 'HRM Introduction',
    descKo: 'HRM의 개념, 역사, 기능, 역할을 체계적으로 학습합니다.',
    descEn: 'Learn the concepts, history, functions, and roles of HRM systematically.',
    color: '#2563EB',
    path: '/hrm-intro',
    topics: ['HRM 개념', '역사적 발전', 'HR 기능', '전략적 HRM', 'HR 부서 역할', 'HRM 환경'],
  },
  {
    id: 'recruitment',
    icon: 'fa-user-plus',
    nameKo: '채용과 선발',
    nameEn: 'Recruitment & Selection',
    descKo: '효과적인 인재 확보를 위한 채용 전략과 선발 기법을 배웁니다.',
    descEn: 'Learn recruitment strategies and selection techniques for effective talent acquisition.',
    color: '#059669',
    path: '/recruitment',
    topics: ['인력계획', '모집 전략', '선발 도구', '면접 기법', '채용 브랜딩', '온보딩'],
  },
  {
    id: 'training',
    icon: 'fa-chalkboard-user',
    nameKo: '교육과 개발',
    nameEn: 'Training & Development',
    descKo: '조직 구성원의 역량 개발과 교육훈련 설계 방법을 학습합니다.',
    descEn: 'Learn competency development and training design methods for organizational members.',
    color: '#8B5CF6',
    path: '/training',
    topics: ['교육 니즈 분석', '교육 설계', '교육 방법론', '경력개발', 'OJT/Off-JT', '교육 평가'],
  },
  {
    id: 'performance',
    icon: 'fa-chart-line',
    nameKo: '성과관리',
    nameEn: 'Performance Management',
    descKo: '공정하고 효과적인 성과관리 시스템 설계와 운영 방법을 배웁니다.',
    descEn: 'Learn to design and operate fair and effective performance management systems.',
    color: '#D97706',
    path: '/performance',
    topics: ['성과관리 개념', 'MBO/KPI/OKR', '평가 방법', '평가 오류', '피드백', '성과 개선'],
  },
  {
    id: 'compensation',
    icon: 'fa-coins',
    nameKo: '보상관리',
    nameEn: 'Compensation Management',
    descKo: '임금 체계, 복리후생, 인센티브 등 보상관리 전반을 학습합니다.',
    descEn: 'Learn overall compensation management including pay systems, benefits, and incentives.',
    color: '#E11D48',
    path: '/compensation',
    topics: ['보상 철학', '임금 체계', '직무 평가', '인센티브', '복리후생', '보상 트렌드'],
  },
  {
    id: 'labor-relations',
    icon: 'fa-handshake',
    nameKo: '노사관계',
    nameEn: 'Labor Relations',
    descKo: '건전한 노사관계 구축과 노동법 기초, 분쟁 해결 방법을 배웁니다.',
    descEn: 'Learn to build healthy labor relations, labor law basics, and dispute resolution.',
    color: '#0891B2',
    path: '/labor-relations',
    topics: ['노사관계 이론', '노동법 기초', '단체교섭', '분쟁 해결', '근로조건', '노사 협력'],
  },
  {
    id: 'org-culture',
    icon: 'fa-building-user',
    nameKo: '조직문화와 리더십',
    nameEn: 'Org Culture & Leadership',
    descKo: '조직문화 형성, 변화관리, 리더십 이론과 실천 방법을 학습합니다.',
    descEn: 'Learn organizational culture formation, change management, and leadership theories.',
    color: '#7C3AED',
    path: '/org-culture',
    topics: ['조직문화 유형', '문화 진단', '변화관리', '리더십 이론', '리더십 스타일', '팀 빌딩'],
  },
  {
    id: 'hr-trends',
    icon: 'fa-rocket',
    nameKo: 'HR 트렌드와 미래',
    nameEn: 'HR Trends & Future',
    descKo: 'AI 시대 HR의 디지털 전환, 원격근무, ESG 등 최신 트렌드를 학습합니다.',
    descEn: 'Learn the latest HR trends including digital transformation, remote work, and ESG.',
    color: '#F59E0B',
    path: '/hr-trends',
    topics: ['HR 디지털 전환', 'AI와 HR', '원격근무', 'ESG/DEI', 'HR 애널리틱스', '미래 HR'],
  },
];
